#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sysuh3c[-1]
	add ucitrack sysuh3c
	set ucitrack.@sysuh3c[-1].init=sysuh3c
	commit ucitrack
	delete sysuh3c.@login[-1]
	add sysuh3c login
	set sysuh3c.@login[-1].enable=0
	set sysuh3c.@login[-1].blockstartup=1
EOF

rm -f /tmp/luci-indexcache
exit 0
