#!/bin/sh /etc/rc.common
START=50

run_h3c()
{
	local enable
	config_get_bool enable $1 enable
	
	if [ $enable ]; then
		local username
		local password
		local method
		local ifname
		
		config_get username $1 username
		config_get password $1 password
		config_get method $1 method
		config_get ifname $1 ifname
		
		echo $password | sysuh3c -u $username -i $ifname -m $method &
		
	fi
}

start()
{
	config_load sysuh3c
	config_foreach run_h3c login
}

stop()
{
	killall sysuh3c >/dev/null 2>&1
}
